c_compiler_version:                       # [unix]
  - 12                                    # [osx]
  - 10                                    # [linux]
cxx_compiler_version:                     # [unix]
  - 12                                    # [osx]
  - 10                                    # [linux]
llvm_openmp:                              # [osx]
  - 12                                    # [osx]
